/*
 * Copyright (c) 2016 SnappyData, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */
package io.snappydata.spark.gemfire.connector.javaapi;

import java.util.Properties;

import io.snappydata.spark.gemfire.connector.GemFirePairRDDFunctions;
import io.snappydata.spark.gemfire.connector.internal.rdd.GemFireJoinRDD;
import io.snappydata.spark.gemfire.connector.internal.rdd.GemFireOuterJoinRDD;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.function.Function;
import scala.Option;
import scala.Tuple2;
import scala.reflect.ClassTag;

import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.emptyStrStrMap;
import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.fakeClassTag;
import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.propertiesToScalaMap;

/**
 * A Java API wrapper over {@link org.apache.spark.api.java.JavaPairRDD} to provide GemFire Spark
 * Connector functionality.
 * <p>
 * <p>To obtain an instance of this wrapper, use one of the factory methods in {@link
 * GemFireJavaUtil} class.</p>
 */
public class GemFireJavaPairRDDFunctions<K, V> {

  public final GemFirePairRDDFunctions<K, V> rddf;

  public GemFireJavaPairRDDFunctions(JavaPairRDD<K, V> rdd) {
    this.rddf = new GemFirePairRDDFunctions<K, V>(rdd.rdd());
  }

  /**
   * Save the pair RDD to GemFire key-value store.
   *
   * @param regionPath the full path of region that the RDD is stored
   * @param opConf     the parameters for this operation
   */
  public void saveToGemFire(String regionPath, Properties opConf) {
    rddf.saveToGemFire(regionPath, propertiesToScalaMap(opConf));
  }


  /**
   * Save the pair RDD to GemFire key-value store.
   *
   * @param regionPath the full path of region that the RDD is stored
   */
  public void saveToGemFire(String regionPath) {
    rddf.saveToGemFire(regionPath, emptyStrStrMap());
  }


  /**
   * Return an JavaPairRDD containing all pairs of elements with matching keys in
   * this RDD&lt;K, V> and the GemFire `Region&lt;K, V2>`. Each pair of elements
   * will be returned as a ((k, v), v2) tuple, where (k, v) is in this RDD and
   * (k, v2) is in the GemFire region.
   *
   * @param regionPath the region path of the GemFire region
   * @param <V2>       the value type of the GemFire region
   * @return JavaPairRDD&lt;&lt;K, V>, V2>
   */
  public <V2> JavaPairRDD<Tuple2<K, V>, V2> joinGemFireRegion(
      String regionPath) {
    GemFireJoinRDD<Tuple2<K, V>, K, V2> rdd = rddf.joinGemFireRegion(regionPath);
    ClassTag<Tuple2<K, V>> kt = fakeClassTag();
    ClassTag<V2> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }


  /**
   * Return an RDD containing all pairs of elements with matching keys in this
   * RDD&lt;K, V> and the GemFire `Region&lt;K2, V2>`. The join key from RDD
   * element is generated by `func(K, V) => K2`, and the key from the GemFire
   * region is just the key of the key/value pair.
   * <p>
   * Each pair of elements of result RDD will be returned as a ((k, v), v2) tuple,
   * where (k, v) is in this RDD and (k2, v2) is in the GemFire region.
   *
   * @param regionPath the region path of the GemFire region
   * @param func       the function that generates region key from RDD element (K, V)
   * @param <K2>       the key type of the GemFire region
   * @param <V2>       the value type of the GemFire region
   * @return JavaPairRDD&lt;Tuple2&lt;K, V>, V2>
   */
  public <K2, V2> JavaPairRDD<Tuple2<K, V>, V2> joinGemFireRegion(
      String regionPath, Function<Tuple2<K, V>, K2> func) {
    GemFireJoinRDD<Tuple2<K, V>, K2, V2> rdd = rddf.joinGemFireRegion(regionPath, func);
    ClassTag<Tuple2<K, V>> kt = fakeClassTag();
    ClassTag<V2> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }


  /**
   * Perform a left outer join of this RDD&lt;K, V> and the GemFire `Region&lt;K, V2>`.
   * For each element (k, v) in this RDD, the resulting RDD will either contain
   * all pairs ((k, v), Some(v2)) for v2 in the GemFire region, or the pair
   * ((k, v), None)) if no element in the GemFire region have key k.
   *
   * @param regionPath the region path of the GemFire region
   * @param <V2>       the value type of the GemFire region
   * @return JavaPairRDD&lt;Tuple2&lt;K, V>, Option&lt;V>>
   */
  public <V2> JavaPairRDD<Tuple2<K, V>, Option<V2>> outerJoinGemFireRegion(
      String regionPath) {
    GemFireOuterJoinRDD<Tuple2<K, V>, K, V2> rdd = rddf.outerJoinGemFireRegion(regionPath);
    ClassTag<Tuple2<K, V>> kt = fakeClassTag();
    ClassTag<Option<V2>> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }


  /**
   * Perform a left outer join of this RDD&lt;K, V> and the GemFire `Region&lt;K2, V2>`.
   * The join key from RDD element is generated by `func(K, V) => K2`, and the
   * key from region is just the key of the key/value pair.
   * <p>
   * For each element (k, v) in `this` RDD, the resulting RDD will either contain
   * all pairs ((k, v), Some(v2)) for v2 in the GemFire region, or the pair
   * ((k, v), None)) if no element in the GemFire region have key `func(k, v)`.
   *
   * @param regionPath the region path of the GemFire region
   * @param func       the function that generates region key from RDD element (K, V)
   * @param <K2>       the key type of the GemFire region
   * @param <V2>       the value type of the GemFire region
   * @return JavaPairRDD&lt;Tuple2&lt;K, V>, Option&lt;V>>
   */
  public <K2, V2> JavaPairRDD<Tuple2<K, V>, Option<V2>> outerJoinGemFireRegion(
      String regionPath, Function<Tuple2<K, V>, K2> func) {
    GemFireOuterJoinRDD<Tuple2<K, V>, K2, V2> rdd = rddf.outerJoinGemFireRegion(regionPath, func);
    ClassTag<Tuple2<K, V>> kt = fakeClassTag();
    ClassTag<Option<V2>> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }

}
