/*
 * Copyright (c) 2016 SnappyData, Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you
 * may not use this file except in compliance with the License. You
 * may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License. See accompanying
 * LICENSE file.
 */
package io.snappydata.spark.gemfire.connector.javaapi;

import java.util.Properties;

import io.snappydata.spark.gemfire.connector.GemFireRDDFunctions;
import io.snappydata.spark.gemfire.connector.internal.rdd.GemFireJoinRDD;
import io.snappydata.spark.gemfire.connector.internal.rdd.GemFireOuterJoinRDD;
import org.apache.spark.api.java.JavaPairRDD;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.function.Function;
import org.apache.spark.api.java.function.PairFunction;
import scala.Option;
import scala.reflect.ClassTag;

import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.emptyStrStrMap;
import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.fakeClassTag;
import static io.snappydata.spark.gemfire.connector.javaapi.JavaAPIHelper.propertiesToScalaMap;

/**
 * A Java API wrapper over {@link org.apache.spark.api.java.JavaRDD} to provide Geode Spark
 * Connector functionality.
 * <p>
 * <p>To obtain an instance of this wrapper, use one of the factory methods in {@link
 * GemFireJavaUtil} class.</p>
 */
public class GemFireJavaRDDFunctions<T> {

  public final GemFireRDDFunctions<T> rddf;

  public GemFireJavaRDDFunctions(JavaRDD<T> rdd) {
    this.rddf = new GemFireRDDFunctions<T>(rdd.rdd());
  }


  /**
   * Save the non-pair RDD to GemFire key-value store.
   *
   * @param regionPath the full path of region that the RDD is stored
   * @param func       the PairFunction that converts elements of JavaRDD to key/value pairs
   */
  public <K, V> void saveToGemFire(
      String regionPath, PairFunction<T, K, V> func) {
    rddf.saveToGemFire(regionPath, func, emptyStrStrMap());
  }

  /**
   * Save the non-pair RDD to GemFire key-value store.
   *
   * @param regionPath the full path of region that the RDD is stored
   * @param func       the PairFunction that converts elements of JavaRDD to key/value pairs
   * @param opConf     the parameters for this operation
   */
  public <K, V> void saveToGemFire(
      String regionPath, PairFunction<T, K, V> func, Properties opConf) {
    rddf.saveToGemFire(regionPath, func, propertiesToScalaMap(opConf));
  }

  /**
   * Return an RDD containing all pairs of elements with matching keys in this
   * RDD&lt;T> and the GemFire `Region&lt;K, V>`. The join key from RDD
   * element is generated by `func(T) => K`, and the key from the GemFire
   * region is just the key of the key/value pair.
   * <p>
   * Each pair of elements of result RDD will be returned as a (t, v2) tuple,
   * where t is from this RDD and v is from the GemFire region.
   *
   * @param regionPath the region path of the GemFire region
   * @param func       the function that generates region key from RDD element T
   * @param <K>        the key type of the GemFire region
   * @param <V>        the value type of the GemFire region
   * @return JavaPairRDD&lt;T, V>
   */
  public <K, V> JavaPairRDD<T, V> joinGemFireRegion(
      String regionPath, Function<T, K> func) {
    GemFireJoinRDD<T, K, V> rdd = rddf.joinGemFireRegion(regionPath, func);
    ClassTag<T> kt = fakeClassTag();
    ClassTag<V> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }


  /**
   * Perform a left outer join of this RDD&lt;T> and the GemFire `Region&lt;K, V>`.
   * The join key from RDD element is generated by `func(T) => K`, and the
   * key from region is just the key of the key/value pair.
   * <p>
   * For each element (t) in this RDD, the resulting RDD will either contain
   * all pairs (t, Some(v)) for v in the GemFire region, or the pair
   * (t, None) if no element in the GemFire region have key `func(t)`.
   *
   * @param regionPath the region path of the GemFire region
   * @param func       the function that generates region key from RDD element T
   * @param <K>        the key type of the GemFire region
   * @param <V>        the value type of the GemFire region
   * @return JavaPairRDD&lt;T, Option&lt;V>>
   */
  public <K, V> JavaPairRDD<T, Option<V>> outerJoinGemFireRegion(
      String regionPath, Function<T, K> func) {
    GemFireOuterJoinRDD<T, K, V> rdd = rddf.outerJoinGemFireRegion(regionPath, func);
    ClassTag<T> kt = fakeClassTag();
    ClassTag<Option<V>> vt = fakeClassTag();
    return new JavaPairRDD<>(rdd, kt, vt);
  }

}
